# Generated by Django 2.2.2 on 2019-06-29 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('skycode', '0003_course_question'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='description',
            field=models.TextField(blank=True, max_length=200, null=True),
        ),
    ]
