# Generated by Django 2.2.2 on 2019-07-03 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('skycode', '0007_news'),
    ]

    operations = [
        migrations.AddField(
            model_name='request',
            name='accepted',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='question',
            name='answered',
            field=models.BooleanField(default=False),
        ),
    ]
