# Generated by Django 2.2.2 on 2019-08-18 16:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('skycode', '0008_auto_20190703_2250'),
    ]

    operations = [
        migrations.RenameField(
            model_name='teacher',
            old_name='first_name',
            new_name='firstName',
        ),
        migrations.RenameField(
            model_name='teacher',
            old_name='last_name',
            new_name='lastName',
        ),
    ]
